apis:
  click2mail:
    root: ./openapi/c2m_openapi_spec_final.yaml

theme:
  openapi:
    schemaExpansionLevel: all
    hideDownloadButton: false
    hideHostname: true

lint:
  extends:
    - recommended

