openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1007
                    name:
                      type: string
                      example: Charlie Jones
                    email:
                      type: string
                      format: email
                      example: john.user4@testsite.com
                    active:
                      type: boolean
                      example: true
                    age:
                      type: integer
                      example: 34
                    createdDate:
                      type: string
                      format: date
                      example: '2025-01-22'
                  example:
                    id: 1007
                    name: Charlie Jones
                    email: john.user4@testsite.com
                    active: true
                    age: 34
                    createdDate: '2025-01-22'
                example:
                - id: 1001
                  name: John Brown
                  email: henry.user1@test.org
                  active: false
                  age: 29
                  createdDate: '2024-10-14'
                - id: 1003
                  name: Eve Davis
                  email: eve.user2@example.com
                  active: false
                  age: 24
                  createdDate: '2025-03-11'
                - id: 1005
                  name: Eve Rodriguez
                  email: charlie.user3@example.com
                  active: true
                  age: 67
                  createdDate: '2024-10-10'
  /products/{id}:
    get:
      summary: Get product by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1009
        productId:
          type: string
          example: productId-074bg92t
        name:
          type: string
          example: Charlie Johnson
        description:
          type: string
          example: This is a module feature widget service component description
        price:
          type: number
          example: 265.0
        inStock:
          type: boolean
          example: false
        quantity:
          type: integer
          example: 81
        tags:
          type: array
          items:
            type: string
            example: tags-3
          example: &id001
          - tags-1
          - tags-2
      example:
        id: 1009
        productId: productId-074bg92t
        name: Charlie Johnson
        description: This is a module feature widget service component description
        price: 265.0
        inStock: false
        quantity: 81
        tags: *id001
