openapi: 3.0.3
info:
  title: Test API
  version: 1.0.0
paths:
  /test:
    post:
      summary: Test endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleRequest'
      responses:
        '200':
          description: OK
components:
  schemas:
    ExampleRequest:
      type: object
      properties:
        name:
          type: string
