name: Run Postman Tests (Dev, Staging, Production)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, staging, production]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection for ${{ matrix.environment }}
      run: |
        mkdir -p results
        newman run postman/lob_postman_collection_monitor_ready.json \
          --environment postman/lob_postman_environment_${{ matrix.environment }}.json \
          --reporters cli,html,junit \
          --reporter-html-export results/report-${{ matrix.environment }}.html \
          --reporter-junit-export results/report-${{ matrix.environment }}.xml

    - name: Upload JUnit Report for ${{ matrix.environment }}
      uses: actions/upload-artifact@v3
      with:
        name: postman-report-${{ matrix.environment }}.xml
        path: results/report-${{ matrix.environment }}.xml

    - name: Upload HTML Report for ${{ matrix.environment }}
      uses: actions/upload-artifact@v3
      with:
        name: html-report-${{ matrix.environment }}
        path: results/report-${{ matrix.environment }}.html

    - name: Mark failure for notifications
      if: failure()
      run: |
        echo "::error ::Postman tests failed in ${{ matrix.environment }}"

    - name: Send Webhook Alert on Failure
      if: failure()
      run: |
        curl -X POST ${{ secrets.POSTMAN_ALERT_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
            "message": "🚨 Postman tests failed in ${{ matrix.environment }}",
            "env": "${{ matrix.environment }}",
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'