name: Build Redoc and Deploy to Pages

on:
  push:
    branches:
      - main
    workflow_dispatch:
    paths-ignore:
      - 'docs/**'  # Avoid loop on docs commit

permissions:
  contents: write  # Needed for committing back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Redoc CLI
        run: npm install -g @redocly/cli

      - name: Build Redoc HTML
        run: |
          mkdir -p docs
          redocly build-docs openapi/c2m_openapi_spec_final.yaml -o docs/index.html

      - name: Commit and push generated docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/index.html
          git commit -m "Update Redoc static docs" || echo "No changes to commit"
          git push

