name: OpenAPI CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate-spec:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Spectral CLI
      run: npm install -g @stoplight/spectral-cli
    - name: Lint Spec
      run: spectral lint lob-api-public.yml