name: PR Drift Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'openapi/**'
      - 'data_dictionary/**'
      - 'scripts/**'
      - 'Makefile'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  drift-check:
    name: Check for uncommitted generated files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; fi
          if [ -f scripts/python_env/requirements.txt ]; then
            pip install -r scripts/python_env/requirements.txt
          fi

      - name: Generate artifacts
        run: |
          echo "🔨 Generating artifacts..."
          make openapi-build
          make postman-collection-build
          make docs

      - name: Check for drift
        id: drift_check
        run: |
          echo "🔍 Checking for uncommitted changes..."
          
          # Check if there are any changes
          if git diff --quiet openapi/ postman/generated/ docs/; then
            echo "✅ All generated files are up to date!"
            echo "drift_found=false" >> $GITHUB_OUTPUT
          else
            echo "❌ Generated files are out of sync!"
            echo "drift_found=true" >> $GITHUB_OUTPUT
            
            # Capture the diff for the PR comment
            echo 'diff<<EOF' >> $GITHUB_OUTPUT
            git diff --stat openapi/ postman/generated/ docs/ >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
            
            # Show detailed changes
            echo ""
            echo "Files changed:"
            git diff --name-only openapi/ postman/generated/ docs/
            
            exit 1
          fi

      - name: Comment on PR
        if: failure() && steps.drift_check.outputs.drift_found == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            ## ⚠️ Generated Files Out of Sync
            
            Your changes require regenerating some files. Please run these commands locally and commit the changes:
            
            \`\`\`bash
            make openapi-build
            make postman-collection-build
            make docs
            git add openapi/ postman/generated/ docs/
            git commit -m "chore: update generated files"
            \`\`\`
            
            <details>
            <summary>📊 Files that need updating</summary>
            
            \`\`\`
            ${{ steps.drift_check.outputs.diff }}
            \`\`\`
            
            </details>
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })